/**
 * Header: /mgi/cvsroot/mgi/mtb/mtbei/src/org/jax/mgi/mtb/ei/panels/CustomPanel.java,v 1.1 2007/04/30 15:50:54 mjv Exp
 * Author: mjv
 */

package org.jax.mgi.mtb.ei.panels;

import javax.swing.JPanel;
import org.jax.mgi.mtb.ei.gui.CustomInternalFrame;
import org.jdesktop.swingworker.SwingWorker;

/**
 * A custom <code>JPanel</code> in which other custom panels should inherit 
 * fromp.
 *
 * @author mjv
 * @version 1.1
 * @cvsheader /mgi/cvsroot/mgi/mtb/mtbei/src/org/jax/mgi/mtb/ei/panels/CustomPanel.java,v 1.1 2007/04/30 15:50:54 mjv Exp
 * @date 2007/04/30 15:50:54
 * @see javax.swing.JPanel
 */
public class CustomPanel extends JPanel {

    // -------------------------------------------------------------- Constants
    // none

    // ----------------------------------------------------- Instance Variables

    protected CustomInternalFrame customInternalFrame = null;
    protected boolean updated = false;

    // ----------------------------------------------------------- Constructors
    /**
     * Creates new form CustomPanel.
     */
    public CustomPanel() {
        initComponents();
        initCustom();
    }

    // --------------------------------------------------------- Public Methods

    public void clear() {
    }

    public void setFrame(CustomInternalFrame cif) {
        this.customInternalFrame = cif;
    }

    public boolean isUpdated() {
        return this.updated;
    }

    public void setUpdated(boolean b) {
        this.updated = b;
    }

    /**
     * Each subclass should override this method to provide save functionality
     * on exit on form.
     */
    public void save() {
    }

    protected void enableComponents(boolean enable) {

    }

    public void quickSave() {
        enableComponents(false);
        SwingWorker worker = new SwingWorker() {
            public Object doInBackground() {
                try {
                    save();
                } catch (Exception e) {

                }
                return "Done";
            }
            public void done() {
                enableComponents(true);
            }
        };

        worker.execute();
    }

    /* TO SLOW
    public void paint(Graphics g) {

        // make it look good
        Graphics2D g2d = (Graphics2D)g;

        g2d.setRenderingHint(
                RenderingHints.KEY_TEXT_ANTIALIASING,
                RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        g2d.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);

        super.paint(g2d);
    }
     */
    
    // ------------------------------------------------------ Protected Methods
    // none

    // -------------------------------------------------------- Private Methods
    
    private void initCustom() {
    }

    // ------------------------------------------------------------------------
    // ------------------------------------------------ NetBeans Generated Code
    // ------------------------------------------------------------------------
    // TAKE EXTREME CARE MODIFYING CODE BELOW THIS LINE
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }
    // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
